name: tiercobblegen
version: '${project.version}'
main: org.patriciachips.tiercobblegen.tiercobblegen
api-version: '1.20'
commands:
  shop:
    aliases:
      - store
  bal:
    aliases:
      - balance
  gen:
    aliases:
      - generator
      - gens
  chestsellall:
    aliases:
      - sellall

permissions:
  tiercobblegen.gen0:
    default: true
  tiercobblegen.gen1:
    default: true
  tiercobblegen.gen2:
    default: false
  tiercobblegen.gen3:
    default: false
  tiercobblegen.gen4:
    default: false
  tiercobblegen.gen5:
    default: false
  tiercobblegen.gen6:
    default: false
  tiercobblegen.gen7:
    default: false
  tiercobblegen.gen8:
    default: false
  tiercobblegen.nethergen1:
    default: false
  tiercobblegen.nethergen2:
    default: false
  tiercobblegen.nethergen3:
    default: false
  tiercobblegen.nethergen4:
    default: false



