name: tiercobblegen
version: '1.0'
main: org.patriciachips.tiercobblegen.tiercobblegen
api-version: '1.20'
commands:
  shop:
    aliases:
      - store
  bal:
    aliases:
      - balance
  gen:
    aliases:
      - generator
      - gens
  chestsellall:
    aliases:
      - sellall
  eco:
    permission: tiercobblegen.eco
  baltop:
  pay:

permissions:
  tiercobblegen.gen0:
    default: true
  tiercobblegen.gen1:
    default: true
  tiercobblegen.gen2:
    default: not op
  tiercobblegen.gen3:
    default: not op
  tiercobblegen.gen4:
    default: not op
  tiercobblegen.gen5:
    default: not op
  tiercobblegen.gen6:
    default: not op
  tiercobblegen.gen7:
    default: not op
  tiercobblegen.gen8:
    default: not op
  tiercobblegen.nethergen1:
    default: not op
  tiercobblegen.nethergen2:
    default: not op
  tiercobblegen.nethergen3:
    default: not op
  tiercobblegen.nethergen4:
    default: not op


